version: "3.9"
services:
  db:
    image: mysql
    platform: linux/x86_64
    container_name: database_codeblack
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "codeblack"
    ports:
      - '3318:3306'
